# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['title']},
        ),
    ]
