# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170523_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='movies',
            field=models.ForeignKey(db_column='movieId', on_delete=django.db.models.deletion.CASCADE, to='movies.Movies', to_field='movieId'),
        ),
    ]
